services:
  human-parser-api:
    build:
      context: .
      args:
        MODEL_ID: ${MODEL_ID:-1ruJg4lqR_jgQPj-9K0PP-L2vJERYOxLP}
        MODEL_NAME: ${MODEL_NAME:-exp-schp-201908301523-atr.pth}
    ports:
      - "8000:8000"
    restart: unless-stopped
